# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-28 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_remove_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='Summary'),
            preserve_default=False,
        ),
    ]
